### ISSUE TITLE
It's always wating

### ISSUE THREAD

**Issue by Sanford284** [fedosejev/react-essentials#102]
when I 'npm start', then open the index.html,console will output "[Snapkite Stream Client] Socket connected".yeah, server is ok. the page is always showing "Waiting for public photos from Twitter...".
is there a problem about my configuration?

**Comment by Sanford284** [comment]
In China.

**Comment by frankgray** [comment]
It cost me half of one weekday to resolve this problem, but i successed.

Because in China persons can't log in twitter, a VPN is required if you want.

So first you should download one VPN software, like Lantern and so on.(I use Lantern in practice.)
And  second remember the proxy url. As to Lantern it is "127.0.0.1:51982".And then double click the VPN to run it.
At last,  edit the file "twitter.js" , it's in "~/snapkite-engine/node_modules/node-tweet-stream/lib".
At line 209, change the code as follows:
```javascript
  this.stream = request.post({
    url: this.twitterUrl,
    oauth: this.oauth,
    form: {
      track: Object.keys(this._filters[FILTER_TYPE_TRACKING]).join(','),
      locations: Object.keys(this._filters[FILTER_TYPE_LOCATION]).join(','),
      follow: Object.keys(this._filters[FILTER_TYPE_FOLLOW]).join(','),
      language: Object.keys(this._filters[FILTER_TYPE_LANGUAGE]).join(',')
    }
  })
```
to:
```javascript
  this.stream = request.post({
    url: this.twitterUrl,
    proxy:'http://127.0.0.1:51598',
    oauth: this.oauth,
    form: {
      track: Object.keys(this._filters[FILTER_TYPE_TRACKING]).join(','),
      locations: Object.keys(this._filters[FILTER_TYPE_LOCATION]).join(','),
      follow: Object.keys(this._filters[FILTER_TYPE_FOLLOW]).join(','),
      language: Object.keys(this._filters[FILTER_TYPE_LANGUAGE]).join(',')
    }
  })
```

Ok , if you finished the steps above , you will enjoy the pictures on your screen.

**Comment by Sanford284** [comment]
thanks, bro.
I have tried your guide. I refer to your code and modify nothing but port(51598 to other). But It still doesn't help.
```
  /*this.stream = request.post({
    url: this.twitterUrl,
    oauth: this.oauth,
    form: {
      track: Object.keys(this._filters[FILTER_TYPE_TRACKING]).join(','),
      locations: Object.keys(this._filters[FILTER_TYPE_LOCATION]).join(','),
      follow: Object.keys(this._filters[FILTER_TYPE_FOLLOW]).join(','),
      language: Object.keys(this._filters[FILTER_TYPE_LANGUAGE]).join(',')
    }
  })*/
  this.stream = request.post({
    url: this.twitterUrl,
    proxy:'http://127.0.0.1:14021',
    oauth: this.oauth,
    form: {
      track: Object.keys(this._filters[FILTER_TYPE_TRACKING]).join(','),
      locations: Object.keys(this._filters[FILTER_TYPE_LOCATION]).join(','),
      follow: Object.keys(this._filters[FILTER_TYPE_FOLLOW]).join(','),
      language: Object.keys(this._filters[FILTER_TYPE_LANGUAGE]).join(',')
    }
  })
```
what's more, I download author's code and install all dependencies, etc. I get the same result.

When I run "npm start" for a while, It give me an Error.
```
C:\Users\real\Desktop\study\snapkite-engine\node_modules\.1.10.0@node-tweet-stream\lib\twitter.js:9
      throw new Error('Exceeded twitter rate limit')
      ^

Error: Exceeded twitter rate limit
    at null.networkBackoff (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.1.10.0@node-tweet-stream\lib\twitt
er.js:9:13)
    at null.<anonymous> (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.1.10.0@node-tweet-stream\lib\twitter.
js:291:13)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.2.79.0@request\request.js:845:8
)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:267:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)

```
Am I connect twitter?

Could I do other to solve the problem? 
Are you a Chinese? Could I connect your QQ or Wechat number? My qq is 1227620310, wechat is "a127620310".

thanks, however!!!

**Comment by Sanford284** [comment]
兄弟，看了你了主页，帮帮我。。 大哭大哭大哭

**Comment by frankgray** [comment]
是的，你已经连上了。并且twitter告诉你连接速度超出了twitter的要求（根据错误的字面意思）
有没有在https://apps.twitter.com/上面注册app？

**Comment by BonLeung** [comment]
I meet the same problem ! when I open the index.html, the page is always showing "Waiting for public photos from Twitter..."

**Comment by Sanford284** [comment]
已经注册了啊，我按照第一章的又查看了一遍，应该没问题的。还有端口问题，我之前用的是shadowsocks，是服务器地址和端口（47.90.13.64:xxx），不知道有没有错。现在在chrome中。设置-》更改代理服务器设置-》连接-》局域网设置-》代理服务器，在twitter.js,line 209,使用了那个地址和端口（127.0.0.1:1080），运行后是：
```
[Snapkite][Socket] Listening on port 3000
[Snapkite][Socket] Client connected
[Snapkite][Socket] Client disconnected
[Snapkite][Socket] Client connected
[Snapkite][Socket] Client disconnected
[Snapkite][Socket] Client connected
[Snapkite][Socket] Client disconnected
[Snapkite][Socket] Client connected
```
然而页面还是没有内容。

过了一会儿，又报错了。超速错误。
```
C:\Users\real\Desktop\study\snapkite-engine\node_modules\.1.10.0@node-tweet-stream\lib\twitter.js:9
      throw new Error('Exceeded twitter rate limit')
      ^

Error: Exceeded twitter rate limit
    at null.networkBackoff (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.1.10.0@node-tweet-stream\lib\twitt
er.js:9:13)
    at null.<anonymous> (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.1.10.0@node-tweet-stream\lib\twitter.
js:291:13)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.2.79.0@request\request.js:845:8
)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at ClientRequest.onError (C:\Users\real\Desktop\study\snapkite-engine\node_modules\.0.4.3@tunnel-agent\index.js:178:
21)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
```

还有一个问题。。这个推文是从哪来的（谁发的推文？）。

**Comment by alexwjm** [comment]
same problem, always waiting ....hope can help asap

**Comment by barbier** [comment]
I'm having the same issue, but outside China and network proxies.
My Snapkite it's exactly configured as the examples so I think it's not a problem with my credentials....

**Comment by chocoest** [comment]
Same problem here !
message : 
 Waiting for public photos from Twitter...                   Your collection is empty
