### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by dannybritto96** [fedosejev/react-essentials#114]
![screenshot at aug 12 07-27-47](https://user-images.githubusercontent.com/21212716/29236860-dcf9c814-7f2f-11e7-986e-51bd446a6b91.png)

This was in the log file 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle snapkite-engine@0.1.2~prestart: snapkite-engine@0.1.2
6 info lifecycle snapkite-engine@0.1.2~start: snapkite-engine@0.1.2
7 verbose lifecycle snapkite-engine@0.1.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle snapkite-engine@0.1.2~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/dannybritto/snapkite-engine/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle snapkite-engine@0.1.2~start: CWD: /Users/dannybritto/snapkite-engine
10 silly lifecycle snapkite-engine@0.1.2~start: Args: [ '-c', 'node app.js' ]
11 silly lifecycle snapkite-engine@0.1.2~start: Returned: code: 1  signal: null
12 info lifecycle snapkite-engine@0.1.2~start: Failed to exec start script
13 verbose stack Error: snapkite-engine@0.1.2 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:897:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
14 verbose pkgid snapkite-engine@0.1.2
15 verbose cwd /Users/dannybritto/snapkite-engine
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.1.2
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error snapkite-engine@0.1.2 start: `node app.js`
22 error Exit status 1
23 error Failed at the snapkite-engine@0.1.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

I'm a noob so please help me resolve this issue @fedosejev

**Comment by danielcolaianni** [comment]
I'm getting the same error. Did you find a solution for it?
Thanks
Daniel
