### ISSUE TITLE
npm start: ERR! missing script: start

### ISSUE THREAD

**Issue by 77leon77** [fedosejev/react-essentials#115]
Hi, 
I have received this error when I try to lunch the npm start command 

npm ERR! missing script: start

Please help me
Thanks
Emilio

**Comment by 77leon77** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:114:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:401:5
4 verbose stack     at handleExists (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:365:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
5 verbose cwd /home/emilio/snapkite-engine
6 verbose Linux 3.16.0-4-amd64
7 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
8 verbose node v8.4.0
9 verbose npm  v5.3.0
10 error missing script: start
11 verbose exit [ 1, true ]
