### ISSUE TITLE
gulp not create app.js

### ISSUE THREAD

**Issue by ucrem** [fedosejev/react-essentials#122]
Hi,

i have this issue. i'm at chapter 1 on page 15. i have created gulpfile.js identicaly but when i launch a gulp command i have an error.
In the issue list most of people have resolved with this gulpfile.js:

`var gulp = require('gulp');
var browserify = require('browserify');
var reactify = require('reactify');
var source = require('vinyl-source-stream');

gulp.task('default', function(){
    return browserify('./source/app.js')
        .transform(reactify, { presets: ["react"] } )
        .bundle()
        .pipe(source('snapterest.js'))
        .pipe(gulp.dest('./build'));
});`

but i have the error:

[21:16:52] Using gulpfile ~/Documents/DEV/snaptrest/gulpfile.js
[21:16:52] Starting 'default'...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/Users/davide/Documents/DEV/snaptrest/source/app.js' from '/Users/davide/Documents/DEV/snaptrest'
    at /Users/davide/Documents/DEV/snaptrest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/davide/Documents/DEV/snaptrest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/davide/Documents/DEV/snaptrest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/davide/Documents/DEV/snaptrest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

on the book is not specified that i have to creare app.js file in source folder but i have tried, but error is the same.
I'm tied to launch gulp command with sudo but is not fixed.

Sorry for my english :)

Thanks in advance

**Comment by giuseppemarasca93** [comment]
ciao Davide, scommetto sei Italiano. A me da lo stesso errore, hai poi risolto? Grazie

**Comment by ucrem** [comment]
> ciao Davide, scommetto sei Italiano. A me da lo stesso errore, hai poi risolto? Grazie

Da cosa l'hai capito? ahahah.
Comunque no non ho risolto, o meglio ho imparato react in altri modi :)
