### ISSUE TITLE
npm start ERROR

### ISSUE THREAD

**Issue by LucaBogani** [fedosejev/react-essentials#124]
npm start does not work.
the errors are:

D:\snapkite-engine\node_modules\node-tweet-stream\node_modules\request\node_modules\hawk\node_modules\boom\lib\index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\snapkite-engine\node_modules\node-tweet-stream\node_modules\request\node_modules\hawk\lib\index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! cwd D:\snapkite-engine
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\snapkite-engine\npm-debug.log
npm ERR! not ok code 0

D:\snapkite-engine>

Please solve this problem!!

**Comment by MaynardTool** [comment]
Same as mine

**Comment by ale-cristofori** [comment]
Hi, 
I am getting this error too. Could it be related to Node version? I googled it online but I have found nothing relevant to this particular package (snapkite-engine) could anyone help?

**Comment by MaynardTool** [comment]
Updating node.js to the latest version resolved my issue
