### ISSUE TITLE
chapter1 cannot run snapkite

### ISSUE THREAD

**Issue by tkanchan** [fedosejev/react-essentials#144]
PS C:\Users\tkanc\gitrepos\snapkite-engine> npm start                                                                                                                                           
> snapkite-engine@0.1.2 start C:\Users\tkanc\gitrepos\snapkite-engine
> node app.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

SyntaxError: C:\Users\tkanc\gitrepos\snapkite-engine\config.json: Unexpected token ] in JSON at position 369
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\tkanc\gitrepos\snapkite-engine\app.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tkanc\AppData\Roaming\npm-cache\_logs\2020-03-04T23_20_38_674Z-debug.log

**Comment by tkanchan** [comment]
I got it. I forgot to remove , from config.json
