### ISSUE TITLE
Error running chapter 5 code...

### ISSUE THREAD

**Issue by joetidee** [fedosejev/react-essentials#27]
I have copied the files from the Chapter 5 directory of Github, run them and get the following error:

```
react@react-vm:~/snapterest$ sudo gulp
[sudo] password for react:
[13:44:59] Using gulpfile ~/snapterest/gulpfile.js
[13:44:59] Starting 'default'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './Collection.react' from '/home/react/snapterest/source/components'
    at /home/react/snapterest/node_modules/resolve/lib/async.js:55:21
    at load (/home/react/snapterest/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/react/snapterest/node_modules/resolve/lib/async.js:92:31)
    at /home/react/snapterest/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I'm assuming that this is becasue one of the component includes is not present, but why is this not in the Chapter 5 directory of Github? Especially when in the last paragraph on page 69 it says "After running snapterest in a web browser for a few mintes..." - clearly this is not the possible to run the code at this point !? This book is becoming an increasingly frustrating read as I cannot continually make the visual connection between the code and what is rendered when the program is run.

**Comment by sebastianwestberg** [comment]
+1 [Duplicate of #6 ](https://github.com/fedosejev/react-essentials/issues/6)

Following the steps in the referenced issue will solve the problem.

**Comment by Schokohuetchen** [comment]
What steps, there's nothing.
