### ISSUE TITLE
Error installing snapkite-stream-client

### ISSUE THREAD

**Issue by rodmunera** [fedosejev/react-essentials#34]
In chapter 1 I successfully installed snapkite engine and started it. it is currently listening on port 3000.

I'm having an issue starting chapter 5 attempting to run `npm install --save snapkite-stream-client`. 
I do have Visual Studio 2008 installed so I don't know why I'm getting that `Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?` error. Is there something else I'm missing?

I'm running a Windows 7 machine.

```
D:\Repositories\snapterest>npm install --save snapkite-stream-client
npm WARN package.json snapterest@1.0.0 No description
npm WARN package.json snapterest@1.0.0 No README data
/
> utf-8-validate@1.2.1 install D:\Repositories\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_m
odules\ws\node_modules\utf-8-validate
> node-gyp rebuild


D:\Repositories\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:122:23)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:104:11
gyp ERR! stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:73:25)
gyp ERR! stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:76:29)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Repositories\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install D:\Repositories\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


D:\Repositories\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node  rebuild )
gyp ERR! build error
gyp ERR! stack Error: Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++ 2008+ installed?
gyp ERR! stack     at findMsbuild (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:122:23)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:104:11
gyp ERR! stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:73:25)
gyp ERR! stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:76:29)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:84:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Repositories\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
snapkite-stream-client@1.0.3 node_modules\snapkite-stream-client
└── socket.io-client@1.3.7 (to-array@0.1.3, debug@0.7.4, indexof@0.0.1, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has
-binary@0.1.6, parseuri@0.0.2, socket.io-parser@2.2.4, engine.io-client@1.5.4)

D:\Repositories\snapterest>
```

**Comment by fedosejev** [comment]
@rodmunera make sure you have the following installed for Windows 7: https://github.com/nodejs/node-gyp#installation

Looks like you need `Microsoft Visual Studio C++ 2013`.

**Comment by rodmunera** [comment]
I did have Visual Studio 2013 installed, but I gave up and started over in my mac.
