### ISSUE TITLE
Error installing snapkite-stream-client

### ISSUE THREAD

**Issue by ravenda900** [fedosejev/react-essentials#36]
I am using Ubuntu 14.04 LTS 64-bit, and having this error.

```
➜  snapterest.dev  npm install --save snapkite-stream-client

> bufferutil@1.2.1 install /var/www/snapterest.dev/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/var/www/snapterest.dev/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: g++: Command not found
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 127
make: Leaving directory `/var/www/snapterest.dev/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-55-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/snapterest.dev/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install /var/www/snapterest.dev/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/var/www/snapterest.dev/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
make: g++: Command not found
make: *** [Release/obj.target/validation/src/validation.o] Error 127
make: Leaving directory `/var/www/snapterest.dev/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-55-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/snapterest.dev/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
npm WARN snapterest.dev@1.0.0 No description
npm WARN snapterest.dev@1.0.0 No repository field.
```

**Comment by fedosejev** [comment]
@ravenda900 looks like you have no `g++` installed: `make: g++: Command not found`

Check https://github.com/nodejs/node-gyp#installation for tools that you need to install.
