### ISSUE TITLE
Error running gulp command

### ISSUE THREAD

**Issue by ravenda900** [fedosejev/react-essentials#37]
I'm already in Chapter 7 and still having this error when running gulp command.

```
➜  snapterest.dev  gulp
[19:35:39] Using gulpfile /var/www/snapterest.dev/gulpfile.js
[19:35:39] Starting 'default'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
SyntaxError: /var/www/snapterest.dev/source/app.js: Unexpected token (5:16)
  3 | var Application = require('./components/Application.react');
  4 | 
> 5 | ReactDOM.render(<Application />, document.getElementById('react-application'));
    |                 ^
    at Parser.pp.raise (/var/www/snapterest.dev/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/var/www/snapterest.dev/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseExprAtom (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:510:12)
    at Parser.pp.parseExprSubscripts (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:265:19)
    at Parser.pp.parseMaybeUnary (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:245:19)
    at Parser.pp.parseExprOps (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:176:19)
    at Parser.pp.parseMaybeConditional (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:158:19)
    at Parser.pp.parseMaybeAssign (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:121:19)
    at Parser.pp.parseExprListItem (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:988:16)
    at Parser.pp.parseCallExpressionArguments (/var/www/snapterest.dev/node_modules/babylon/lib/parser/expression.js:341:20)
```

**Comment by fedosejev** [comment]
@ravenda900 try running: `npm install --save-dev babelify@^6.2.0` or do the following: https://github.com/fedosejev/react-essentials/issues/21#issuecomment-160316774
