### ISSUE TITLE
Cannot find modules

### ISSUE THREAD

**Issue by ghost** [fedosejev/react-essentials#51]
Apparently, there are few modules missing that are required by snapkite-stream-client which are not mentioned:
-bufferutil
-utf-8-validate

**Comment by fedosejev** [comment]
@nemigaservices can you please explain why do you need these modules?

**Comment by konradszydlo** [comment]
@nemigaservices I had the same problem. See @davidrf https://github.com/fedosejev/react-essentials/issues/54#issuecomment-170425570. It worked for me.

**Comment by davidrf** [comment]
@fedosejev right after I added `snapkite-stream-client`. I got the following errors on my build (they alternated).

```
$ gulp
[12:46:36] Using gulpfile C:\gitproject\snapterest\gulpfile.js
[12:46:36] Starting 'default'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'bufferutil' from 'C:\gitproject\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib'
    at C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

```
$ gulp
[12:46:36] Using gulpfile C:\gitproject\snapterest\gulpfile.js
[12:46:36] Starting 'default'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'utf-8-validate' from 'C:\gitproject\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib'
    at C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Based on the stack trace, we can see that `snapkite-stream-client` has a chained node module dependency on [`ws`](https://github.com/websockets/ws#opt-in-for-performance) and that's where it is trying to find the `bufferutil` and `utf-8-validate` modules. It seems that [`bufferutils` and `utf-8-validate` recently went from being optionalDependencies to devDependencies](https://github.com/websockets/ws/commit/49b11093e9a009e5305dcde7003d3a896b2811dc). According, to the [`ws README.md`](https://github.com/websockets/ws#opt-in-for-performance), we must now `npm install bufferutil utf-8-validate --save` in order to utilize these features. I am assuming that `snapkite-stream-client`'s dependecy on `socket.io-client` needs these dependencies to properly function. I'd probably recommend adding these modules as dependencies on your `snapkite-stream-client` repo.

**Comment by fedosejev** [comment]
@davidrf thanks a lot for the detailed explanation! I didn't manage to reproduce that problem on OSX, yet.

Could this be Windows-specific issue?

**Comment by djdman2000** [comment]
I am running on OS X and followed the solution from @davidrf. The build of snapterest on Page 113 of the book worked as expected after running `npm install bufferutil utf-8-validate --save`.
