### ISSUE TITLE
console error 

### ISSUE THREAD

**Issue by tanmoyb** [fedosejev/react-essentials#52]
tanmoy@IDEA-PC ~/desktop/reactee/snapkite-engine (master)
$ node app.js
module.js:453
    throw err;
    ^

SyntaxError: c:\Users\tanmoy\desktop\reactee\snapkite-engine\config.json: Unexpe
cted token
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\Users\tanmoy\desktop\reactee\snapkite-engine\app.j
s:1:85)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by fedosejev** [comment]
@tanmoyb there is a syntax error in `c:\Users\tanmoy\desktop\reactee\snapkite-engine\config.json` file. Can you please post it here, so I could take a look?

**Comment by tanmoyb** [comment]
its ok now , my mongodb database was not configured , anyway thank u very much and highly appreciate your reply in such a sort time .

**Comment by fedosejev** [comment]
@tanmoyb thanks for reading the book! :+1:
