### ISSUE TITLE
gulp error: Cannot find module 'bufferutil' 

### ISSUE THREAD

**Issue by Chiva-Zhao** [fedosejev/react-essentials#54]
When I execute gulp at the end of Chapter 7, it happens following errors, please help me.

```
air@Macbook MINGW64 /c/gitproject/snapterest
$ gulp
[12:46:36] Using gulpfile C:\gitproject\snapterest\gulpfile.js
[12:46:36] Starting 'default'...
I am about to learn the essentials of React.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'bufferutil' from 'C:\gitproject\snapterest\node_modules\snapkite-stream-client\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\lib'
    at C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\gitproject\snapterest\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

```

**Comment by davidrf** [comment]
I have the same problem =\

**Comment by davidrf** [comment]
@Chiva-Zhao I had the same problem, resolved it by `npm install bufferutil utf-8-validate --save`.

**Comment by Chiva-Zhao** [comment]
@davidrf  Thanks for your answer, when i execute `npm install bufferutil utf-8-validate --save`
I got following error in my WIN 8 computer,

```
> bufferutil@1.2.1 install C:\gitproject\snapterest\node_modules\bufferutil
> node-gyp rebuild


C:\gitproject\snapterest\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:121:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\gitproject\snapterest\node_modules\bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bufferutil" "utf-8-validate" "--save"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utf-8-validate@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls utf-8-validate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\gitproject\snapterest\npm-debug.log
```

I think it's my python 3 cause the problem.

**Comment by fedosejev** [comment]
@Chiva-Zhao yes, you're right - Python 3 is not supported according to the docs for `node-gyp` module: https://github.com/nodejs/node-gyp

Python `v2.7.10` is recommended.
