### ISSUE TITLE
NPM start page 7

### ISSUE THREAD

**Issue by RachBLondon** [fedosejev/react-essentials#65]
Hi I am having diffculty getting my app to start after I have installed all the snap kite filters, it says there is an unexpected token the config.json file:

```
> snapkite-engine@0.1.2 start /Users/rachelblack/Documents/Projects/learning/react/book-packet-react/snapkite-engine
> node app.js

module.js:463
    throw err;
    ^

SyntaxError: /Users/rachelblack/Documents/Projects/learning/react/book-packet-react/snapkite-engine/config.json: Unexpected token   
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:460:27)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/rachelblack/Documents/Projects/learning/react/book-packet-react/snapkite-engine/app.js:1:85)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rachelblack/Documents/Projects/learning/react/book-packet-react/snapkite-engine/npm-debug.log
```

Here is my config.json (I have XXed out the API keys and host address)

```
{
  "application": {
    "pushTweets": true,
    "storeTweets": false,
    "pushKeywords": false,
    "storeKeywords": false,
    "trackKeywords": "",
    "excludeKeywords": "",
    "filters": ["snapkite-filter-is-possibly-sensitive",
      "snapkite-filter-has-mobile-photo",
      "snapkite-filter-is-retweet",
      "snapkite-filter-has-text"
    ]
  },
  "twitter": {
    "api": {
      "consumerKey": "XXXX",
      "consumerSecret": "   XXXXX",
      "accessTokenKey": "XXXXX",
      "accessTokenSecret": "XXXXXXXX"
    }
  },
  "database": {
    "hostname": "XXXX",
    "port": "27017",
    "username": "",
    "password": "",
    "name": "snapkite"
  },
  "socket": {
    "port": 3000
  }
```

**Comment by alaingoldman** [comment]
I dont know if this is the solution but you're missing a closing curly brace at the end of the config.json

**Comment by alaingoldman** [comment]
also you could just download the project files and see if you still get the error at this chapter. I dont think you would but who knows :p

**Comment by RachBLondon** [comment]
Thanks alot I shall try both those things :-)
