### ISSUE TITLE
Ch. 8, Failing test on CollectionUtils-test.js

### ISSUE THREAD

**Issue by CampbellD84** [fedosejev/react-essentials#66]
Hello, 

After creating the CollectionUtils-test file, I ran the tests and I keep getting 2 failed tests even though both tests should pass. Here are the test results:

sing Jest CLI v0.4.18
 FAIL  source/utils/**tests**/TweetUtils-test.js
TypeError: Cannot read property 'length' of undefined
  at maybeReadMore_ (_stream_readable.js:431:18)
  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickCallback (node.js:381:13)

/home/dcdev/snapturest/node_modules/node-worker-pool/Worker.js:106
    throw new Error('Received unexpected data from child process: ' + data);
    ^

Error: Received unexpected data from child process: {
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at process._tickCallback (node.js:381:13)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate (timers.js:383:17)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at process._tickCallback (node.js:381:13)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}
{
  "error": "TypeError: Cannot read property 'length' of undefined\n  at onwriteDrain (_stream_writable.js:354:12)\n  at afterWrite (_stream_writable.js:344:5)\n  at /home/dcdev/snapturest/node_modules/jest-cli/src/lib/FakeTimers.js:342:7\n  at nextTickCallbackWith0Args (node.js:452:9)\n  at Immediate._tickCallback [as _onImmediate](node.js:381:13)\n  at processImmediate [as _immediateCallback](timers.js:383:17)\n"
}

  at Worker._onStdout (/home/dcdev/snapturest/node_modules/node-worker-pool/Worker.js:106:11)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:147:16)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at Pipe.onread (net.js:523:20)

npm ERR! Test failed.  See above for more details.

Thank you

**Comment by myshov** [comment]
I think you have some incompatibility between version of node.js and jest. For me node.js v4.2.1 and jest v.0.8.2 works just fine. By the way check this issue for more information https://github.com/fedosejev/react-essentials/issues/67

Also maybe there is some typo in your code, anyway you can check this code in your environment https://github.com/fedosejev/react-essentials/blob/master/code/chapter08/snapterest/source/utils/__tests__/CollectionUtils-test.js
