### ISSUE TITLE
npm start ERROR.

### ISSUE THREAD

**Issue by gtanju** [fedosejev/react-essentials#70]
tanjus-iMac:snapkite-engine root# npm start

> snapkite-engine@0.1.2 start /private/var/root/snapkite-engine
> node app.js

module.js:433
    throw err;
    ^

SyntaxError: /private/var/root/snapkite-engine/config.json: Unexpected token “
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/private/var/root/snapkite-engine/app.js:1:85)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/root/snapkite-engine/npm-debug.log
tanjus-iMac:snapkite-engine root# 

NOW THE LOG FILE...

tanjus-iMac:snapkite-engine root# ls
.git                README.md           controllers         models              package.json
.gitignore          app.js              example.config.json     node_modules            snapkite-engine-logo.png
LICENSE             config.json         filters             npm-debug.log           utils.js
tanjus-iMac:snapkite-engine root# more npm*
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle snapkite-engine@0.1.2~prestart: snapkite-engine@0.1.2
6 silly lifecycle snapkite-engine@0.1.2~prestart: no script for prestart, continuing
7 info lifecycle snapkite-engine@0.1.2~start: snapkite-engine@0.1.2
8 verbose lifecycle snapkite-engine@0.1.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle snapkite-engine@0.1.2~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/private/var/root/snapkite-engine/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle snapkite-engine@0.1.2~start: CWD: /private/var/root/snapkite-engine
11 silly lifecycle snapkite-engine@0.1.2~start: Args: [ '-c', 'node app.js' ]
12 silly lifecycle snapkite-engine@0.1.2~start: Returned: code: 1  signal: null
13 info lifecycle snapkite-engine@0.1.2~start: Failed to exec start script
14 verbose stack Error: snapkite-engine@0.1.2 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid snapkite-engine@0.1.2
16 verbose cwd /private/var/root/snapkite-engine
17 error Darwin 15.3.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error snapkite-engine@0.1.2 start: `node app.js`
22 error Exit status 1
23 error Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the snapkite-engine package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs snapkite-engine
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls snapkite-engine
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tnguven** [comment]
+1

**Comment by fedosejev** [comment]
@gtanju notice the error message: `Unexpected token “`

The problem is the `“` character in your `/private/var/root/snapkite-engine/config.json` file - it's a different double quote character from a normal `"`. Please use `"` instead.

P.S. Thanks for getting the book!
