### ISSUE TITLE
Chapter 1: getting snapkite up and running...

### ISSUE THREAD

**Issue by Prufrock1** [fedosejev/react-essentials#72]
Any suggestions here? I get an error when I try to run

snapkite-engine developer1$ npm start

> snapkite-engine@0.1.2 start /Users/developer1/Desktop/Projects/react.js_esentials/snapkite-engine
> node app.js

[Snapkite][Socket] Listening on port 3000

module.js:340
    throw err;
    ^
Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/developer1/Desktop/Projects/react.js_esentials/snapkite-engine/filters/snapkite-filter-is-retweet/index.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the snapkite-engine@0.1.2 start script.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.3.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/developer1/Desktop/Projects/react.js_esentials/snapkite-engine
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/developer1/Desktop/Projects/react.js_esentials/snapkite-engine/npm-debug.log
npm ERR! not ok code 0

**Comment by Prufrock1** [comment]
So I was able to fix it, turns out I was missing the config.json in filers/snapkite-filter-is-retweet/
