### ISSUE TITLE
Chapter 8: Testing React components (pages 129-131).

### ISSUE THREAD

**Issue by matthewlynch** [fedosejev/react-essentials#8]
Hi, 

When running `npm test` after finishing `Header-test.js` an error is thrown:

```
$ npm test

> snapterest@1.0.0 test /path/to/snapterest
> jest

Using Jest CLI v0.5.5
 PASS  source/utils/__tests__/TweetUtils-test.js (0.017s)
 PASS  source/utils/__tests__/CollectionUtils-test.js (0.022s)
 FAIL  source/components/__tests__/Header-test.js 
● Runtime Error
SyntaxError: /path/to/snapterest/source/components/__tests__/Header-test.js: Unexpected token <
  at Object.exports.runInContext (vm.js:43:16)
  at JSDomEnvironment.runSourceText (/path/to/snapterest/node_modules/jest-cli/src/JSDomEnvironment.js:86:8)
  at Object.runContentWithLocalBindings (/path/to/snapterest/node_modules/jest-cli/src/lib/utils.js:498:17)
  at Loader._execModule (/path/to/snapterest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:236:9)
  at Loader.requireModule (/path/to/snapterest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:905:12)
  at jasmineTestRunner (/path/to/snapterest/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:284:16)
  at /path/to/snapterest/node_modules/jest-cli/src/TestRunner.js:375:12

1 test failed, 2 tests passed (3 total)
Run time: 1.011s
npm ERR! Test failed.  See above for more details.
```

After some digging around I found this link: https://facebook.github.io/jest/docs/tutorial-react.html#setup. I needed to install `babel-jest` and add this to my `package.json` file: 

```
"jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react"
    ]
  }
```

Leaving this here for anyone else who might run into this problem.

Using 
node: 4.1.0
npm: 2.14.3
react: 0.14.0-rc1
jest: 0.5.5 (i upgraded to 0.5.7 and got the same error before updating my `package.json` file)

**Comment by matthewlynch** [comment]
Maybe if I was a little more patient I would have saved some time as this is shown a little further on in the book!

**Comment by djheru** [comment]
Thanks, I was doing the same thing!

**Comment by backslash112** [comment]
After doing this, i got a new error: 
![image](https://cloud.githubusercontent.com/assets/5343215/11418390/5029f470-945a-11e5-9ba1-628d5f928bc2.png)

**Comment by backslash112** [comment]
Thank you, @matthewlynch  This works for me!! ^0^  a little different with you:

```
"jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react",
      "<rootDir>/node_modules/react-dom",
      "<rootDir>/node_modules/react-addons-test-utils",
      "<rootDir>/node_modules/fbjs"
    ]
  },
```

BTW, using
node: 4.1.1
npm: 3.4.1
react: 0.14.3
jest: 0.8.0

**Comment by kwokster10** [comment]
Hi, I'm running into the same error. I installed babel-jest and package.json looks like @backslash112. I tried running it on node v5.5.0, 4.2.6, and 4.1.1 with the same error 

```
 FAIL  __tests__/app_test.js 
● Runtime Error
SyntaxError: /Users/cyrusadmin/Cyrus/HighLine/__tests__/app_test.js: Unexpected token (15:43)
  13 | describe('App', function(){
  14 |   it('initial state is set to Map', function(){
> 15 |     var app = TestUtils.renderIntoDocument(<App/>);
     |                                            ^
  16 |     expect(app.state).toEqual({
  17 |       page: 'Map'
  18 |     });
    at Parser.pp.raise (/Users/.../node_modules/babel-jest/node_modules/babel-core/node_modules/babylon/index.js:1425:13)
```

current run:
node v4.1.1
npm v2.14.4

```
"jest": {
    "scriptPreprocessor": "<rootDir>/node_modules/babel-jest",
    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react",
      "<rootDir>/node_modules/react-dom",
      "<rootDir>/node_modules/react-addons-test-utils",
      "<rootDir>/node_modules/fbjs",
      "promise",
      "source-map"
    ],
```
