### ISSUE TITLE
Chapter 1 npm start

### ISSUE THREAD

**Issue by antoleo** [fedosejev/react-essentials#90]
**I saw this issue is already posted but I can't solved.thks**

> snapkite-engine@0.1.2 start c:\deposito\snapkite-engine
> node app.js

module.js:427
    throw err;
    ^

SyntaxError: c:\deposito\snapkite-engine\config.json: Unexpected token }
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\deposito\snapkite-engine\app.js:1:85)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! snapkite-engine@0.1.2 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snapkite-engine@0.1.2 start script 'node app.js'.
npm ERR! This is most likely a problem with the snapkite-engine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snapkite-engine
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls snapkite-engine
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\deposito\snapkite-engine\npm-debug.log

**Comment by antoleo** [comment]
I've solved it. A wrong character in config.json
